apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-search-service
  template:
    metadata:
      labels:
        app: app-search-service
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: app-creds
            items:
              - key: sa_json
                path: sa_credentials.json
      containers:
        - name: app-search-service
          image: gcr.io/${your.google.cloud.project}/app-search-service:v1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: google-cloud-key
              mountPath: /etc/gcp
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json